# Generated by Django 3.2 on 2024-02-26 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_auto_20240226_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='achievement',
            new_name='achievements',
        ),
    ]
